
# video parameters
DOOR_STREAM_PORTS = (5000,)
DOOR_RTSP_PORTS = (8000,)
SKIP_FRAMES_MAX = 2
USB_CAM_NUM = 1
USB_CAMERA = '/dev/video{}'.format(USB_CAM_NUM)
USB_CAMERA_FORMAT = 'NV12'  # could be 'MJPEG'
USB_CAMERA_FRAME_SHAPE = (1280, 720)  # (640, 480,)
USB_CAMERA_FPS = 30
VIDEO_OUT_FRAME_SHAPE = (1280, 720)  # (800, 600,)
VIDEO_OUT_BITRATE = 8000000
DISPLAY_SIZE = (1680, 1050)  # (840, 525,)
ASPECT_RATIO = (16, 10,)
ACTIVE_REMAIN_TIME = 4
FRAME_SIZE_FOR_DNN = (300, 300)
SHOW_ON_DISPLAY = True
FINAL_FRAME_DELTA_MINUS = 8

# door management parameters
USE_WIEGAND = False
SEND_CARD_ID = False
LEDON_REMAIN_TIME = 3
GPIO_RELAY_PINS = (5, 19, 13, 6)  # # relay id = 1, 2, 3, 4
DOOR_SLEEP_TIME = 5
LOG_DOOR_EVENTS = False

# recognition parameters
LIVENESS_TEST = False
FACES_SAVE_INTERVAL = 6
LOG_UNKNOWN_FACES = False
LOG_KNOWN_USERS = False
ROBUST_SEEN_TIMES = 4
ROBUST_SEEN_INTERVAL = 2
FACE_DETECTOR_THRESHOLD = 0.2
FACE_RECOGNITION_ALLOWED_DISTANCE = 0.5
